// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BiofalsaDocumentDataSlicesSlice =
  | CoseNonPiaccionoSlice
  | CosePiaccionoSlice
  | BioVeraSlice
  | BarraHonestSlice
  | BioFalsaSlice;

/**
 * Content for Bio documents
 */
interface BiofalsaDocumentData {
  /**
   * Slice Zone field in *Bio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: biofalsa.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BiofalsaDocumentDataSlicesSlice>;
}

/**
 * Bio document from Prismic
 *
 * - **API ID**: `biofalsa`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BiofalsaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BiofalsaDocumentData>,
    "biofalsa",
    Lang
  >;

type BiometadatiDocumentDataSlicesSlice = never;

/**
 * Content for BioMetadati documents
 */
interface BiometadatiDocumentData {
  /**
   * Slice Zone field in *BioMetadati*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: biometadati.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BiometadatiDocumentDataSlicesSlice> /**
   * Meta Title field in *BioMetadati*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: biometadati.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *BioMetadati*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: biometadati.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *BioMetadati*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: biometadati.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * BioMetadati document from Prismic
 *
 * - **API ID**: `biometadati`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BiometadatiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BiometadatiDocumentData>,
    "biometadati",
    Lang
  >;

type CookiePolicyDocumentDataSlicesSlice = CookiePolicySlice;

/**
 * Content for Cookie policy documents
 */
interface CookiePolicyDocumentData {
  /**
   * Slice Zone field in *Cookie policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CookiePolicyDocumentDataSlicesSlice> /**
   * Meta Title field in *Cookie policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cookie_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Cookie policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cookie_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Cookie policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Cookie policy document from Prismic
 *
 * - **API ID**: `cookie_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CookiePolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CookiePolicyDocumentData>,
    "cookie_policy",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | WhoIsPioSlice
  | ContattiHSlice
  | PortfolioHomeSlice
  | WorkSchoolSlice
  | HeroHomeSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type ImpostazioniDocumentDataSlicesSlice = FooterSlice;

/**
 * Content for Impostazioni documents
 */
interface ImpostazioniDocumentData {
  /**
   * Slice Zone field in *Impostazioni*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: impostazioni.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ImpostazioniDocumentDataSlicesSlice>;
}

/**
 * Impostazioni document from Prismic
 *
 * - **API ID**: `impostazioni`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImpostazioniDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ImpostazioniDocumentData>,
    "impostazioni",
    Lang
  >;

type MenuDocumentDataSlicesSlice = LinkMenuSlice;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Slice Zone field in *Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MenuDocumentDataSlicesSlice>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PortfolioDocumentDataSlicesSlice = GallerySlice | InformazioniSlice;

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Order field in *Portfolio*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioDocumentData>,
    "portfolio",
    Lang
  >;

type PortfoliopageDocumentDataSlicesSlice = PortfolioInfoSlice;

/**
 * Content for PortfolioPage documents
 */
interface PortfoliopageDocumentData {
  /**
   * Slice Zone field in *PortfolioPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfoliopage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfoliopageDocumentDataSlicesSlice> /**
   * Meta Title field in *PortfolioPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfoliopage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *PortfolioPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfoliopage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PortfolioPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfoliopage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * PortfolioPage document from Prismic
 *
 * - **API ID**: `portfoliopage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfoliopageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortfoliopageDocumentData>,
    "portfoliopage",
    Lang
  >;

export type AllDocumentTypes =
  | BiofalsaDocument
  | BiometadatiDocument
  | CookiePolicyDocument
  | HomepageDocument
  | ImpostazioniDocument
  | MenuDocument
  | PortfolioDocument
  | PortfoliopageDocument;

/**
 * Primary content in *BarraHonest → Default → Primary*
 */
export interface BarraHonestSliceDefaultPrimary {
  /**
   * TestoHonest field in *BarraHonest → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_honest.default.primary.testohonest
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testohonest: prismic.KeyTextField;
}

/**
 * Default variation for BarraHonest Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BarraHonestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BarraHonestSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BarraHonest*
 */
type BarraHonestSliceVariation = BarraHonestSliceDefault;

/**
 * BarraHonest Shared Slice
 *
 * - **API ID**: `barra_honest`
 * - **Description**: BarraHonest
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BarraHonestSlice = prismic.SharedSlice<
  "barra_honest",
  BarraHonestSliceVariation
>;

/**
 * Item in *BioFalsa → Default → Primary → Bio*
 */
export interface BioFalsaSliceDefaultPrimaryBioItem {
  /**
   * Frase field in *BioFalsa → Default → Primary → Bio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.bio[].frase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  frase: prismic.KeyTextField;

  /**
   * Accento field in *BioFalsa → Default → Primary → Bio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.bio[].accento
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accento: prismic.KeyTextField;

  /**
   * Punto dopo field in *BioFalsa → Default → Primary → Bio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: bio_falsa.default.primary.bio[].punto_dopo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  punto_dopo: prismic.BooleanField;
}

/**
 * Primary content in *BioFalsa → Default → Primary*
 */
export interface BioFalsaSliceDefaultPrimary {
  /**
   * Bio field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.bio[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bio: prismic.GroupField<Simplify<BioFalsaSliceDefaultPrimaryBioItem>>;

  /**
   * Keep scrolling field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.keep_scrolling
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keep_scrolling: prismic.KeyTextField;

  /**
   * FotoFalsaBuona field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.fotofalsabuona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotofalsabuona: prismic.ImageField<never>;

  /**
   * FotoFalsaCattiva field in *BioFalsa → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_falsa.default.primary.fotofalsacattiva
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotofalsacattiva: prismic.ImageField<never>;
}

/**
 * Default variation for BioFalsa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioFalsaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BioFalsaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BioFalsa*
 */
type BioFalsaSliceVariation = BioFalsaSliceDefault;

/**
 * BioFalsa Shared Slice
 *
 * - **API ID**: `bio_falsa`
 * - **Description**: BioFalsa
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioFalsaSlice = prismic.SharedSlice<
  "bio_falsa",
  BioFalsaSliceVariation
>;

/**
 * Item in *BioVera → Default → Primary → Bio*
 */
export interface BioVeraSliceDefaultPrimaryBioItem {
  /**
   * Frase field in *BioVera → Default → Primary → Bio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.bio[].frase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  frase: prismic.KeyTextField;

  /**
   * Accento field in *BioVera → Default → Primary → Bio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.bio[].accento
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accento: prismic.KeyTextField;

  /**
   * Punto dopo field in *BioVera → Default → Primary → Bio*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: bio_vera.default.primary.bio[].punto_dopo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  punto_dopo: prismic.BooleanField;
}

/**
 * Primary content in *BioVera → Default → Primary*
 */
export interface BioVeraSliceDefaultPrimary {
  /**
   * Bio field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.bio[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bio: prismic.GroupField<Simplify<BioVeraSliceDefaultPrimaryBioItem>>;

  /**
   * Foto Buona field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.foto_buona
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto_buona: prismic.ImageField<never>;

  /**
   * Foto gatti 1 field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.foto_gatti_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto_gatti_1: prismic.ImageField<never>;

  /**
   * Foto gatti 2 field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.foto_gatti_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto_gatti_2: prismic.ImageField<never>;

  /**
   * Foto gatti 3 field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.foto_gatti_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto_gatti_3: prismic.ImageField<never>;

  /**
   * Foto gatti 4 field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.foto_gatti_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto_gatti_4: prismic.ImageField<never>;

  /**
   * Testo gatti field in *BioVera → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_vera.default.primary.testo_gatti
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_gatti: prismic.KeyTextField;
}

/**
 * Default variation for BioVera Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioVeraSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BioVeraSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BioVera*
 */
type BioVeraSliceVariation = BioVeraSliceDefault;

/**
 * BioVera Shared Slice
 *
 * - **API ID**: `bio_vera`
 * - **Description**: BioVera
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BioVeraSlice = prismic.SharedSlice<
  "bio_vera",
  BioVeraSliceVariation
>;

/**
 * Primary content in *Contatti → Default → Primary*
 */
export interface ContattiHSliceDefaultPrimary {
  /**
   * Titolo contatti field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.titolo_contatti
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_contatti: prismic.KeyTextField;

  /**
   * Copy contatti field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.copy_contatti
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_contatti: prismic.KeyTextField;

  /**
   * Titolo mail field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.titolo_mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_mail: prismic.KeyTextField;

  /**
   * Mail field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * Link mail field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.link_mail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_mail: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Titolo luogo field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.titolo_luogo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_luogo: prismic.KeyTextField;

  /**
   * Testo luogo field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.testo_luogo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_luogo: prismic.KeyTextField;

  /**
   * Quote contatti field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.quote_contatti
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote_contatti: prismic.KeyTextField;

  /**
   * Autore quote field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.autore_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  autore_quote: prismic.KeyTextField;

  /**
   * Immagine contatti field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.immagine_contatti
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_contatti: prismic.ImageField<never>;

  /**
   * Info sito field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.info_sito
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info_sito: prismic.KeyTextField;

  /**
   * Testo tasto scopri field in *Contatti → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contatti_h.default.primary.testo_tasto_scopri
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto_scopri: prismic.KeyTextField;
}

/**
 * Default variation for Contatti Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContattiHSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContattiHSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contatti*
 */
type ContattiHSliceVariation = ContattiHSliceDefault;

/**
 * Contatti Shared Slice
 *
 * - **API ID**: `contatti_h`
 * - **Description**: ContattiH
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContattiHSlice = prismic.SharedSlice<
  "contatti_h",
  ContattiHSliceVariation
>;

/**
 * Item in *CookiePolicy → Default → Primary → Paragrafi*
 */
export interface CookiePolicySliceDefaultPrimaryParagrafiItem {
  /**
   * Titolo paragrafo field in *CookiePolicy → Default → Primary → Paragrafi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.default.primary.paragrafi[].titolo_paragrafo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_paragrafo: prismic.KeyTextField;

  /**
   * Testo paragrafo field in *CookiePolicy → Default → Primary → Paragrafi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.default.primary.paragrafi[].testo_paragrafo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo_paragrafo: prismic.RichTextField;
}

/**
 * Primary content in *CookiePolicy → Default → Primary*
 */
export interface CookiePolicySliceDefaultPrimary {
  /**
   * Titolo field in *CookiePolicy → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Paragrafi field in *CookiePolicy → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie_policy.default.primary.paragrafi[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  paragrafi: prismic.GroupField<
    Simplify<CookiePolicySliceDefaultPrimaryParagrafiItem>
  >;
}

/**
 * Default variation for CookiePolicy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CookiePolicySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CookiePolicySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CookiePolicy*
 */
type CookiePolicySliceVariation = CookiePolicySliceDefault;

/**
 * CookiePolicy Shared Slice
 *
 * - **API ID**: `cookie_policy`
 * - **Description**: CookiePolicy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CookiePolicySlice = prismic.SharedSlice<
  "cookie_policy",
  CookiePolicySliceVariation
>;

/**
 * Item in *CoseNonPiacciono → Default → Primary → Cosa*
 */
export interface CoseNonPiaccionoSliceDefaultPrimaryCosaItem {
  /**
   * Nome cosa field in *CoseNonPiacciono → Default → Primary → Cosa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_non_piacciono.default.primary.cosa[].nome_cosa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_cosa: prismic.KeyTextField;

  /**
   * Gif cosa field in *CoseNonPiacciono → Default → Primary → Cosa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_non_piacciono.default.primary.cosa[].gif_cosa
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gif_cosa: prismic.ImageField<never>;
}

/**
 * Primary content in *CoseNonPiacciono → Default → Primary*
 */
export interface CoseNonPiaccionoSliceDefaultPrimary {
  /**
   * Titolo cose non piacciono field in *CoseNonPiacciono → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_non_piacciono.default.primary.titolo_cose_non_piacciono
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_cose_non_piacciono: prismic.KeyTextField;

  /**
   * Cosa field in *CoseNonPiacciono → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_non_piacciono.default.primary.cosa[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cosa: prismic.GroupField<
    Simplify<CoseNonPiaccionoSliceDefaultPrimaryCosaItem>
  >;
}

/**
 * Default variation for CoseNonPiacciono Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoseNonPiaccionoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoseNonPiaccionoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoseNonPiacciono*
 */
type CoseNonPiaccionoSliceVariation = CoseNonPiaccionoSliceDefault;

/**
 * CoseNonPiacciono Shared Slice
 *
 * - **API ID**: `cose_non_piacciono`
 * - **Description**: CoseNonPiacciono
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoseNonPiaccionoSlice = prismic.SharedSlice<
  "cose_non_piacciono",
  CoseNonPiaccionoSliceVariation
>;

/**
 * Item in *CosePiacciono → Default → Primary → Cosa*
 */
export interface CosePiaccionoSliceDefaultPrimaryCosaItem {
  /**
   * Nome cosa field in *CosePiacciono → Default → Primary → Cosa*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_piacciono.default.primary.cosa[].nome_cosa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_cosa: prismic.KeyTextField;

  /**
   * Gif cosa field in *CosePiacciono → Default → Primary → Cosa*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_piacciono.default.primary.cosa[].gif_cosa
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gif_cosa: prismic.ImageField<never>;
}

/**
 * Primary content in *CosePiacciono → Default → Primary*
 */
export interface CosePiaccionoSliceDefaultPrimary {
  /**
   * Titolo cose piacciono field in *CosePiacciono → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_piacciono.default.primary.titolo_cose_piacciono
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_cose_piacciono: prismic.KeyTextField;

  /**
   * Cosa field in *CosePiacciono → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cose_piacciono.default.primary.cosa[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cosa: prismic.GroupField<Simplify<CosePiaccionoSliceDefaultPrimaryCosaItem>>;
}

/**
 * Default variation for CosePiacciono Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CosePiaccionoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CosePiaccionoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CosePiacciono*
 */
type CosePiaccionoSliceVariation = CosePiaccionoSliceDefault;

/**
 * CosePiacciono Shared Slice
 *
 * - **API ID**: `cose_piacciono`
 * - **Description**: CosePiacciono
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CosePiaccionoSlice = prismic.SharedSlice<
  "cose_piacciono",
  CosePiaccionoSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Social*
 */
export interface FooterSliceDefaultPrimarySocialItem {
  /**
   * Nome social field in *Footer → Default → Primary → Social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social[].nome_social
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_social: prismic.KeyTextField;

  /**
   * Link social field in *Footer → Default → Primary → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social[].link_social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_social: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Mail field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * Testo mail field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_mail: prismic.KeyTextField;

  /**
   * Link mail field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.link_mail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_mail: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Testo dettagli sviluppo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_dettagli_sviluppo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_dettagli_sviluppo: prismic.KeyTextField;

  /**
   * Disclaimer field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.disclaimer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  disclaimer: prismic.KeyTextField;

  /**
   * Copyright field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Testo iva field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_iva
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_iva: prismic.KeyTextField;

  /**
   * Partita iva field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.partita_iva
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  partita_iva: prismic.KeyTextField;

  /**
   * Testo social field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_social
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_social: prismic.KeyTextField;

  /**
   * Social field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<FooterSliceDefaultPrimarySocialItem>>;

  /**
   * Link cookie field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.link_cookie
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_cookie: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Testo cookie field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.testo_cookie
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_cookie: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Gallery → Default → Primary → Screen desktop*
 */
export interface GallerySliceDefaultPrimaryScreenDesktopItem {
  /**
   * Screen field in *Gallery → Default → Primary → Screen desktop*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.screen_desktop[].screen
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screen: prismic.ImageField<never>;

  /**
   * Spiega field in *Gallery → Default → Primary → Screen desktop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.screen_desktop[].spiega
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega: prismic.KeyTextField;
}

/**
 * Item in *Gallery → Default → Primary → Screen mobile*
 */
export interface GallerySliceDefaultPrimaryScreenMobileItem {
  /**
   * Screen field in *Gallery → Default → Primary → Screen mobile*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.screen_mobile[].screen
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screen: prismic.ImageField<never>;

  /**
   * Spiega field in *Gallery → Default → Primary → Screen mobile*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.screen_mobile[].spiega
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spiega: prismic.KeyTextField;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Screen desktop field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.screen_desktop[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  screen_desktop: prismic.GroupField<
    Simplify<GallerySliceDefaultPrimaryScreenDesktopItem>
  >;

  /**
   * Screen mobile field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.screen_mobile[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  screen_mobile: prismic.GroupField<
    Simplify<GallerySliceDefaultPrimaryScreenMobileItem>
  >;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Item in *HeroHome → Default → Primary → Elenco lista*
 */
export interface HeroHomeSliceDefaultPrimaryElencoListaItem {
  /**
   * Bullet point field in *HeroHome → Default → Primary → Elenco lista*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.elenco_lista[].bullet_point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bullet_point: prismic.KeyTextField;
}

/**
 * Primary content in *HeroHome → Default → Primary*
 */
export interface HeroHomeSliceDefaultPrimary {
  /**
   * Titolo Hero field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.titolo_hero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titolo_hero: prismic.RichTextField;

  /**
   * Testo hero field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.testo_hero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testo_hero: prismic.RichTextField;

  /**
   * Sfondo Hero field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.sfondo_hero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sfondo_hero: prismic.ImageField<never>;

  /**
   * Gfi stella field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.gfi_stella
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gfi_stella: prismic.ImageField<never>;

  /**
   * Testo lista field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.testo_lista
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_lista: prismic.KeyTextField;

  /**
   * Elenco lista field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.elenco_lista[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  elenco_lista: prismic.GroupField<
    Simplify<HeroHomeSliceDefaultPrimaryElencoListaItem>
  >;
}

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroHomeSliceVariation = HeroHomeSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero_home`
 * - **Description**: HeroHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSlice = prismic.SharedSlice<
  "hero_home",
  HeroHomeSliceVariation
>;

/**
 * Primary content in *Informazioni → Default → Primary*
 */
export interface InformazioniSliceDefaultPrimary {
  /**
   * Titolo field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: informazioni.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Made with field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: informazioni.default.primary.made_with
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  made_with: prismic.SelectField<
    "Wordpress" | "Elementor" | "React" | "Vue" | "Shopify"
  >;

  /**
   * Testo tasto field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: informazioni.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link progetto field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: informazioni.default.primary.link_progetto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_progetto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Visibile field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: informazioni.default.primary.visibile
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  visibile: prismic.BooleanField;

  /**
   * Messaggio non visibile field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: informazioni.default.primary.messaggio_non_visibile
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  messaggio_non_visibile: prismic.KeyTextField;

  /**
   * Descrizione progetto field in *Informazioni → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: informazioni.default.primary.descrizione_progetto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descrizione_progetto: prismic.KeyTextField;
}

/**
 * Default variation for Informazioni Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformazioniSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InformazioniSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Informazioni*
 */
type InformazioniSliceVariation = InformazioniSliceDefault;

/**
 * Informazioni Shared Slice
 *
 * - **API ID**: `informazioni`
 * - **Description**: Informazioni
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformazioniSlice = prismic.SharedSlice<
  "informazioni",
  InformazioniSliceVariation
>;

/**
 * Item in *LinkMenu → Default → Primary → Link*
 */
export interface LinkMenuSliceDefaultPrimaryLinkItem {
  /**
   * Testo link field in *LinkMenu → Default → Primary → Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_menu.default.primary.link[].testo_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_link: prismic.KeyTextField;

  /**
   * Link field in *LinkMenu → Default → Primary → Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_menu.default.primary.link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *LinkMenu → Default → Primary*
 */
export interface LinkMenuSliceDefaultPrimary {
  /**
   * Link field in *LinkMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_menu.default.primary.link[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link: prismic.GroupField<Simplify<LinkMenuSliceDefaultPrimaryLinkItem>>;
}

/**
 * Default variation for LinkMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkMenu*
 */
type LinkMenuSliceVariation = LinkMenuSliceDefault;

/**
 * LinkMenu Shared Slice
 *
 * - **API ID**: `link_menu`
 * - **Description**: LinkMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkMenuSlice = prismic.SharedSlice<
  "link_menu",
  LinkMenuSliceVariation
>;

/**
 * Item in *PortfolioHome → Default → Primary → Progetti*
 */
export interface PortfolioHomeSliceDefaultPrimaryProgettiItem {
  /**
   * Nome field in *PortfolioHome → Default → Primary → Progetti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Screen desktop field in *PortfolioHome → Default → Primary → Progetti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[].screen_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screen_desktop: prismic.ImageField<never>;

  /**
   * Screen mobile field in *PortfolioHome → Default → Primary → Progetti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[].screen_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screen_mobile: prismic.ImageField<never>;

  /**
   * Made with field in *PortfolioHome → Default → Primary → Progetti*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[].made_with
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  made_with: prismic.SelectField<
    "Wordpress" | "Elementor" | "React" | "Vue" | "Shopify"
  >;

  /**
   * Bg color field in *PortfolioHome → Default → Primary → Progetti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[].bg_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bg_color: prismic.KeyTextField;

  /**
   * Discover more field in *PortfolioHome → Default → Primary → Progetti*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[].discover_more
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  discover_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *PortfolioHome → Default → Primary*
 */
export interface PortfolioHomeSliceDefaultPrimary {
  /**
   * Titolo portfolio field in *PortfolioHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.titolo_portfolio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_portfolio: prismic.KeyTextField;

  /**
   * Copy portfolio field in *PortfolioHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.copy_portfolio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_portfolio: prismic.KeyTextField;

  /**
   * Progetti field in *PortfolioHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.progetti[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  progetti: prismic.GroupField<
    Simplify<PortfolioHomeSliceDefaultPrimaryProgettiItem>
  >;

  /**
   * Copy vedere altro field in *PortfolioHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.copy_vedere_altro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_vedere_altro: prismic.KeyTextField;

  /**
   * Testo tasto altro field in *PortfolioHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.testo_tasto_altro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto_altro: prismic.KeyTextField;

  /**
   * Link altro field in *PortfolioHome → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_home.default.primary.link_altro
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_altro: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for PortfolioHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PortfolioHome*
 */
type PortfolioHomeSliceVariation = PortfolioHomeSliceDefault;

/**
 * PortfolioHome Shared Slice
 *
 * - **API ID**: `portfolio_home`
 * - **Description**: PortfolioHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioHomeSlice = prismic.SharedSlice<
  "portfolio_home",
  PortfolioHomeSliceVariation
>;

/**
 * Primary content in *PortfolioInfo → Default → Primary*
 */
export interface PortfolioInfoSliceDefaultPrimary {
  /**
   * Titolo field in *PortfolioInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_info.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Copy field in *PortfolioInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_info.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy: prismic.KeyTextField;
}

/**
 * Default variation for PortfolioInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PortfolioInfo*
 */
type PortfolioInfoSliceVariation = PortfolioInfoSliceDefault;

/**
 * PortfolioInfo Shared Slice
 *
 * - **API ID**: `portfolio_info`
 * - **Description**: PortfolioInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioInfoSlice = prismic.SharedSlice<
  "portfolio_info",
  PortfolioInfoSliceVariation
>;

/**
 * Primary content in *WhoIsPio → Default → Primary*
 */
export interface WhoIsPioSliceDefaultPrimary {
  /**
   * Titolo field in *WhoIsPio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_is_pio.default.primary.titolo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * Testo field in *WhoIsPio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_is_pio.default.primary.testo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo: prismic.KeyTextField;

  /**
   * Immagine field in *WhoIsPio → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: who_is_pio.default.primary.immagine
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine: prismic.ImageField<never>;

  /**
   * Testo tasto field in *WhoIsPio → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_is_pio.default.primary.testo_tasto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testo_tasto: prismic.KeyTextField;

  /**
   * Link tasto field in *WhoIsPio → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: who_is_pio.default.primary.link_tasto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_tasto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for WhoIsPio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhoIsPioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhoIsPioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhoIsPio*
 */
type WhoIsPioSliceVariation = WhoIsPioSliceDefault;

/**
 * WhoIsPio Shared Slice
 *
 * - **API ID**: `who_is_pio`
 * - **Description**: WhoIsPio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhoIsPioSlice = prismic.SharedSlice<
  "who_is_pio",
  WhoIsPioSliceVariation
>;

/**
 * Item in *WorkSchool → Default → Primary → Works*
 */
export interface WorkSchoolSliceDefaultPrimaryWorksItem {
  /**
   * Work position field in *WorkSchool → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.works[].work_position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_position: prismic.KeyTextField;

  /**
   * Dove field in *WorkSchool → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.works[].dove
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dove: prismic.KeyTextField;

  /**
   * Periodo field in *WorkSchool → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.works[].periodo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  periodo: prismic.KeyTextField;

  /**
   * Attuale field in *WorkSchool → Default → Primary → Works*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: work_school.default.primary.works[].attuale
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  attuale: prismic.BooleanField;
}

/**
 * Item in *WorkSchool → Default → Primary → Studies*
 */
export interface WorkSchoolSliceDefaultPrimaryStudiesItem {
  /**
   * Nome corso field in *WorkSchool → Default → Primary → Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.studies[].nome_corso
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_corso: prismic.KeyTextField;

  /**
   * Dove field in *WorkSchool → Default → Primary → Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.studies[].dove
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dove: prismic.KeyTextField;

  /**
   * Periodo field in *WorkSchool → Default → Primary → Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.studies[].periodo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  periodo: prismic.KeyTextField;
}

/**
 * Item in *WorkSchool → Default → Primary → Certificazioni*
 */
export interface WorkSchoolSliceDefaultPrimaryCertificazioniItem {
  /**
   * Nome certificazione field in *WorkSchool → Default → Primary → Certificazioni*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.certificazioni[].nome_certificazione
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_certificazione: prismic.KeyTextField;

  /**
   * Dove field in *WorkSchool → Default → Primary → Certificazioni*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.certificazioni[].dove
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dove: prismic.KeyTextField;

  /**
   * Quando field in *WorkSchool → Default → Primary → Certificazioni*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.certificazioni[].quando
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quando: prismic.KeyTextField;
}

/**
 * Primary content in *WorkSchool → Default → Primary*
 */
export interface WorkSchoolSliceDefaultPrimary {
  /**
   * Title field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Work title field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.work_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_title: prismic.KeyTextField;

  /**
   * Work copy field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.work_copy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_copy: prismic.KeyTextField;

  /**
   * Works field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.works[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  works: prismic.GroupField<Simplify<WorkSchoolSliceDefaultPrimaryWorksItem>>;

  /**
   * Study title field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.study_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  study_title: prismic.KeyTextField;

  /**
   * Study copy field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.study_copy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  study_copy: prismic.KeyTextField;

  /**
   * Studies field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.studies[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  studies: prismic.GroupField<
    Simplify<WorkSchoolSliceDefaultPrimaryStudiesItem>
  >;

  /**
   * Titolo Certificazioni field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.titolo_certificazioni
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo_certificazioni: prismic.KeyTextField;

  /**
   * Copy certificazioni field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.copy_certificazioni
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_certificazioni: prismic.KeyTextField;

  /**
   * Certificazioni field in *WorkSchool → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_school.default.primary.certificazioni[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  certificazioni: prismic.GroupField<
    Simplify<WorkSchoolSliceDefaultPrimaryCertificazioniItem>
  >;
}

/**
 * Default variation for WorkSchool Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSchoolSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkSchoolSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkSchool*
 */
type WorkSchoolSliceVariation = WorkSchoolSliceDefault;

/**
 * WorkSchool Shared Slice
 *
 * - **API ID**: `work_school`
 * - **Description**: WorkSchool
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSchoolSlice = prismic.SharedSlice<
  "work_school",
  WorkSchoolSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BiofalsaDocument,
      BiofalsaDocumentData,
      BiofalsaDocumentDataSlicesSlice,
      BiometadatiDocument,
      BiometadatiDocumentData,
      BiometadatiDocumentDataSlicesSlice,
      CookiePolicyDocument,
      CookiePolicyDocumentData,
      CookiePolicyDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ImpostazioniDocument,
      ImpostazioniDocumentData,
      ImpostazioniDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      PortfoliopageDocument,
      PortfoliopageDocumentData,
      PortfoliopageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BarraHonestSlice,
      BarraHonestSliceDefaultPrimary,
      BarraHonestSliceVariation,
      BarraHonestSliceDefault,
      BioFalsaSlice,
      BioFalsaSliceDefaultPrimaryBioItem,
      BioFalsaSliceDefaultPrimary,
      BioFalsaSliceVariation,
      BioFalsaSliceDefault,
      BioVeraSlice,
      BioVeraSliceDefaultPrimaryBioItem,
      BioVeraSliceDefaultPrimary,
      BioVeraSliceVariation,
      BioVeraSliceDefault,
      ContattiHSlice,
      ContattiHSliceDefaultPrimary,
      ContattiHSliceVariation,
      ContattiHSliceDefault,
      CookiePolicySlice,
      CookiePolicySliceDefaultPrimaryParagrafiItem,
      CookiePolicySliceDefaultPrimary,
      CookiePolicySliceVariation,
      CookiePolicySliceDefault,
      CoseNonPiaccionoSlice,
      CoseNonPiaccionoSliceDefaultPrimaryCosaItem,
      CoseNonPiaccionoSliceDefaultPrimary,
      CoseNonPiaccionoSliceVariation,
      CoseNonPiaccionoSliceDefault,
      CosePiaccionoSlice,
      CosePiaccionoSliceDefaultPrimaryCosaItem,
      CosePiaccionoSliceDefaultPrimary,
      CosePiaccionoSliceVariation,
      CosePiaccionoSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimarySocialItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimaryScreenDesktopItem,
      GallerySliceDefaultPrimaryScreenMobileItem,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroHomeSlice,
      HeroHomeSliceDefaultPrimaryElencoListaItem,
      HeroHomeSliceDefaultPrimary,
      HeroHomeSliceVariation,
      HeroHomeSliceDefault,
      InformazioniSlice,
      InformazioniSliceDefaultPrimary,
      InformazioniSliceVariation,
      InformazioniSliceDefault,
      LinkMenuSlice,
      LinkMenuSliceDefaultPrimaryLinkItem,
      LinkMenuSliceDefaultPrimary,
      LinkMenuSliceVariation,
      LinkMenuSliceDefault,
      PortfolioHomeSlice,
      PortfolioHomeSliceDefaultPrimaryProgettiItem,
      PortfolioHomeSliceDefaultPrimary,
      PortfolioHomeSliceVariation,
      PortfolioHomeSliceDefault,
      PortfolioInfoSlice,
      PortfolioInfoSliceDefaultPrimary,
      PortfolioInfoSliceVariation,
      PortfolioInfoSliceDefault,
      WhoIsPioSlice,
      WhoIsPioSliceDefaultPrimary,
      WhoIsPioSliceVariation,
      WhoIsPioSliceDefault,
      WorkSchoolSlice,
      WorkSchoolSliceDefaultPrimaryWorksItem,
      WorkSchoolSliceDefaultPrimaryStudiesItem,
      WorkSchoolSliceDefaultPrimaryCertificazioniItem,
      WorkSchoolSliceDefaultPrimary,
      WorkSchoolSliceVariation,
      WorkSchoolSliceDefault,
    };
  }
}
