// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  barra_honest: dynamic(() => import("./BarraHonest")),
  bio_falsa: dynamic(() => import("./BioFalsa")),
  bio_vera: dynamic(() => import("./BioVera")),
  contatti_h: dynamic(() => import("./Contatti")),
  cookie_policy: dynamic(() => import("./CookiePolicy")),
  cose_non_piacciono: dynamic(() => import("./CoseNonPiacciono")),
  cose_piacciono: dynamic(() => import("./CosePiacciono")),
  footer: dynamic(() => import("./Footer")),
  gallery: dynamic(() => import("./Gallery")),
  hero_home: dynamic(() => import("./HeroHome")),
  informazioni: dynamic(() => import("./Informazioni")),
  link_menu: dynamic(() => import("./LinkMenu")),
  portfolio_home: dynamic(() => import("./PortfolioHome")),
  portfolio_info: dynamic(() => import("./PortfolioInfo")),
  who_is_pio: dynamic(() => import("./WhoIsPio")),
  work_school: dynamic(() => import("./WorkSchool")),
};
